trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self  
  persistCredentials: true
  fetchDepth: 0
  clean: true

- script: |
    echo "Listing local branches..."
    git fetch origin '+refs/heads/*:refs/heads/*'
    echo "Local branches:"
    git branch -a
  displayName: 'Fetching branches'

- script: |
    echo "Configuring Git..."    
    git config user.email "jokubynas@gmail.com"
    git config user.name "ArunasJok"

    echo "Running repository maintenance..."
    git repack -a -d
    git gc

    # Create or use personal access token as a pipeline variable
    # Replace with a secure Azure DevOps pipeline variable
    GITHUB_PAT=$(GITHUB_TOKEN)
    
    echo "Adding GitHub remote..."
    # Check if main branch exists and use it without creating
    git branch -a | grep -q "main" && git checkout main || git checkout -b main
    
    # Use the variable for authentication
    git remote remove github 2>/dev/null || true
    git remote add github "https://$GITHUB_PAT@github.com/ArunasJok/Dish-Discover.git"

    echo "Pushing changes to GitHub..."
    # Force push to override potential conflicts
    git push -u github main --force

    echo "Pushing all tags to GitHub..."
    git push github --tags
  displayName: 'Push changes to GitHub'
  env:    
    GITHUB_TOKEN: $(GITHUB_TOKEN)